### ISSUE TITLE
words to add to glossary

### ISSUE THREAD

**Issue by saskiad** [AllenSWDB/allenswdb.github.io#1]
- [x] fast spiking unit
- [x] regular spiking unit
- [x] waveform
- [x] LFP

**Comment by saskiad** [comment]
I would mention that FS units are thought to be inhibitory, including PV and SST interneurons. RS units are thought to be excitatory, but do include VIP interneurons.

**Comment by galenlynch** [comment]
I don't normally associate SST neurons with fast-spiking neurons. Many SST neurons don't have narrow action potentials.

**Comment by saskiad** [comment]
According to the literature and the data I've seen they do. I can believe
that not ALL classes of SST neurons have narrow action potentials, but
definitely many do.

**Comment by galenlynch** [comment]
Well, faster than pyramidal neurons but my impression from the literature that sub 400 us is mostly PV+. Anna's paper in auditory cortex shows SST+ neurons have intermediate peak to trough times, while PV+ neurons have the shortest (https://www.jneurosci.org/content/40/18/3564/tab-figures-data). Patch recordings (e.g. https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4159120/figure/pbio-1001944-g001/) show similar longer SST+ APs compared to PV+. However, I'm not an expert.

Maybe given the diversity of PV+ interneurons and SST+ interneurons we could just say it's complicated but I've personally always assume people were talking about PV+ neurons when they say fast spiking interneurons.

**Comment by alakunina** [comment]
The general assumption I've seen is that fast-spiking units are specifically PV+ (at least in cortex)
