### ISSUE TITLE
unit quality metrics note

### ISSUE THREAD

**Issue by saskiad** [AllenSWDB/allenswdb.github.io#110]
I would add a box admonition or something like that to emphasize that visual coding default returns only the units that pass qc while visual behavior default returns all units regardless of qc.

**Comment by JEElsner** [comment]
There's already a note in [Background > Extracellular Electrophysiology > Unit Quality Metrics # Tutorial Overview](https://allenswdb.github.io/physiology/ephys/visual-coding/vcnp-quality-metrics.html#tutorial-overview).

Is this sufficient?
Should there be notes elsewhere?
Should this be upgraded to an admonition/warning from a note?

**Comment by saskiad** [comment]
yeah, it is - sorry, I completely just missed this before!
