### ISSUE TITLE
Add computational tutorials: regression

### ISSUE THREAD

**Issue by saskiad** [AllenSWDB/allenswdb.github.io#37]

**Comment by saskiad** [comment]
- [ ] Get tutorial(s)
- [ ] Review tutorial pedagogically
- [ ] Review example

**Comment by matchings** [comment]
I believe that the day 1 workshop 1 notebook can be used for the regression tutorial: https://github.com/AllenInstitute/swdb_neural_encoding/blob/main/code/Day1Workshop1.ipynb
