### ISSUE TITLE
what other computational tutorials do we want

### ISSUE THREAD

**Issue by saskiad** [AllenSWDB/allenswdb.github.io#39]

**Comment by mabuice** [comment]
Any Basic Statistics?


Expansion of clustering/classification into other examples
K-Means
GMM
Random Forrest
Logistic Regression
Parametric vs non-parametric?


Other feature selection approaches
Boosting?

Model Selection?


PyTorch tutorial (also Jax?)

Basic feedforward nets
CNNs

Fitting RNNs to activity

Autoencoders (connected to neural theories)
VAEs?

Common Data Processing techniques for common modalities

Git Tutorial

Other open tools?
 VSCode?

**Comment by mabuice** [comment]
example of why and when to use each clustering/classification algorithm

**Comment by saskiad** [comment]
Expansion of clustering/classification into other examples
K-Means
GMM
Random Forrest
Logistic Regression
Parametric vs non-parametric?

Other feature selection approaches
Boosting?

Model Selection?

PyTorch tutorial (also Jax?)

Basic feedforward nets
CNNs

**Comment by JEElsner** [comment]
A basic tutorial on how to navigate and use various features of Code Ocean would be useful.
