### ISSUE TITLE
Add visual-behavior-ophys_project_manifest_v1.1.0 as data asset in SWDB databook capsule 

### ISSUE THREAD

**Issue by matchings** [AllenSWDB/allenswdb.github.io#48]
The SWDB databook Code Ocean [capsule](https://codeocean.allenneuraldynamics.org/capsule/7837120/tree) only includes VBO datasets up to v1.0.1, but needs to include the final version of NWB files associated with manifest v1.1.0

The final NWB files should be accessible on AWS at https://visual-behavior-ophys-data.s3-us-west-2.amazonaws.com/ and more info on how to access them is included in [this notebook](https://allensdk.readthedocs.io/en/latest/_static/examples/nb/visual_behavior_ophys_data_access.html). 

The main change in the final NWB files is to add a `stimulus_block` to the `stimulus_presentations` table, which allows users to access timestamps for the 5 min gray screen periods and the natural movie clip shown at the end of ophys sessions. It also includes several changes to column names and metadata to align with the Visual Behavior Neuropixels dataset functionality in the AllenSDK, which makes the datasets more easily cross-analyzeable.

A [PR](https://github.com/AllenSWDB/allenswdb.github.io/pulls) on the databook tutorials for VBO has already been made to add the code needed to access and filter the stimulus blocks so that users can utilize this information, however it is only accessible if the final NWBs are provided along with the databook.

**Comment by saskiad** [comment]
which PR is it? I see two VBO PRs that have merge conflicts that need resolving before they can be merged.

**Comment by matchings** [comment]
I merged the two VBO PRs into this one: https://github.com/AllenSWDB/allenswdb.github.io/pull/41

**Comment by matchings** [comment]
I believe this is now fixed, as David reindexed / refreshed the VBO data asset and the v1.1.0 manifest shows up. I will do some tests to double check that everything works as expected. 

<img width="634" alt="image" src="https://github.com/AllenSWDB/allenswdb.github.io/assets/21346970/712126b9-4a62-4251-9d50-905f70964943">

**Comment by matchings** [comment]
I looked at a capsule with the data asset and loaded the manifests and the numbers of sessions & cells line up with what i would expect for v1.1.0, and the `stimulus_block_name` column shows up in the `stimulus_presentations` table. I think we can call this done.
