### ISSUE TITLE
Missing images

### ISSUE THREAD

**Issue by galenlynch** [AllenSWDB/allenswdb.github.io#7]
@corbennett two images that the visual behavior section, `AB_images.png`, and `GH_images.png` are not in the repo, and do not appear to have ever been in the repo. I searched through all past commits with the following command:
```
git log --all --full-history -- '**/AB_images.png'
```
And found nothing.

I will replace the images with some stand-in to eliminate the build error for now.

**Comment by matchings** [comment]
Thanks for noting this Galen, I am going to make a branch of the repo and fix these issues as well as a few other errors I have noticed in the visual behavior section. No need to add stand ins just yet.
