### ISSUE TITLE
CTLUT citations

### ISSUE THREAD

**Issue by saskiad** [AllenSWDB/allenswdb.github.io#73]

**Comment by saskiad** [comment]
Talk with Anna Lakunina about what citations need to be added.

**Comment by JEElsner** [comment]
Issue is [here](https://allenswdb.github.io/physiology/ephys/cell-type-lookup-table/ctlut-background.html?highlight=citations#background): "(CITATIONS)".

**Comment by JEElsner** [comment]
We got this fixed during the workshop.
