### ISSUE TITLE
Fix error in Behavior Session Data

### ISSUE THREAD

**Issue by saskiad** [AllenSWDB/allenswdb.github.io#75]
Some code in this section fails: https://allenswdb.github.io/physiology/stimuli/visual-behavior/VB-BehaviorSessionData.html#aggregate-data-across-all-behavior-sessions-for-this-mouse

**Comment by saskiad** [comment]
Talk to @matchings or Vergil about what's going on here

**Comment by matchings** [comment]
Hmm i am confused by this. If the code is using the NWB files via the same attached data asset as was used in last year's course, and is using allensdk 2.15.2, as it indicates in the notebook, there shouldn't be any problem loading the files. Actually, even the newest version of allensdk, 2.16.2, should be backwards compatible and able to load older files. 

Maybe this is a dumb question, but are you sure the VB data asset is attached? 

<img width="608" alt="image" src="https://github.com/AllenSWDB/allenswdb.github.io/assets/21346970/cc1ddb8c-c4aa-42d2-aec4-c49eb93f8526">

**Comment by JEElsner** [comment]
I just checked, and it runs on my machine, which indicates you're right: there's a problem with the capsule that builds the databook. I'll look into the capsule on Friday, but I haven't done much in that capsule yet, so it might take some time.

**Comment by JEElsner** [comment]
I was able to get it to build properly without the error in my own copy of the CodeOcean build capsule. I'll need to check in with @d-w-liu about how he's building it.

**Comment by JEElsner** [comment]
This is working as of the latest databook build. I'm not really sure what changed, to be honest, so we'll see if it crops up again.

A couple notes
* This cell still throws *a lot* of warnings (but no errors), taking up a lot of the page
* There is now a new error further down the page (see issue __)
