### ISSUE TITLE
Fix miscellaneous databook formatting warnings

### ISSUE THREAD

**Issue by JEElsner** [AllenSWDB/allenswdb.github.io#83]
# TOC errors
Files appearing in the TOC that don't exist, or files that exist but aren't in the TOC. Some of these might be fixed by one of @d-w-liu 's PRs, and some we might not care about, given the databook restructuring.
- [x] `background/Neuropixels-electrophysiology.md` toc nonexistent reference to `physiology/ephys/neuropixels-description`
- [ ] `background/Intrinsic-Signal-Imaging.md` Not in TOC
- [x] `physiology/stimuli/visual-behavior/vb-background.md` Not in TOC

# Formatting
- [x] `background/Neuropixels-description.md:1` Page should start with `<h1>` (`#`) instead of `<h2>` (`##`)

# Build log warnings
```
/opt/databook/databook/background/Neuropixels-electrophysiology.md:: WARNING: toctree contains reference to nonexisting document 'physiology/ephys/neuropixels-description' [etoc.ref]

/opt/databook/databook/background/neuropixels-description.md:1: WARNING: Document headings start at H2, not H1 [myst.header]

checking consistency... /opt/databook/databook/background/Intrinsic-Signal-Imaging.md: WARNING: document isn't included in any toctree
/opt/databook/databook/background/neuropixels-description.md: WARNING: document isn't included in any toctree
/opt/databook/databook/physiology/stimuli/visual-behavior/vb-background.md: WARNING: document isn't included in any toctree
```

**Comment by d-w-liu** [comment]
These issues were resolved in a previous PR; ISI is intended to not be in the TOC
