### ISSUE TITLE
Fix broken video in `vc2p-background.md`

### ISSUE THREAD

**Issue by JEElsner** [AllenSWDB/allenswdb.github.io#99]
In the section [Physiology > Ophys > VC2P > Experiment](https://allenswdb.github.io/physiology/ophys/visual-coding/vc2p-background.html#experiment) there is a video that fails to load.

**Comment by saskiad** [comment]
The mp4 file in the resources folder plays correctly for me - I assume for you too? So this has something to do with playing it in the book?

**Comment by JEElsner** [comment]
Yeah I presume the URL in the markdown points to the wrong place.
